import Head from "next/head";

const MetaTages = () => {
  return (
    <Head>
      <title>It Vallely</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
  );
};

export default MetaTages;
