import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

const MetaTages = () => {
  const router = useRouter();
  const title =
    router.pathname !== "/"
      ? router.pathname.replaceAll("/", " >> ")
      : "";
  return (
    <Head>
      <title>It Vallely {title}</title>
      <meta
        name='description'
        content='Generated by create next app'
      />
      <link rel='icon' href='/fav_icon.png' />
    </Head>
  );
};

export default MetaTages;
